name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '20' 
      - uses: actions/setup-node@v3
        with:
          node-version: '20' 
          registry-url: 'https://registry.npmjs.org/'
      - name: CI
        run: npm ci
      - name: Semantic Release
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify Node-RED Library
        if: success() && github.ref == 'refs/heads/master' # Ensure this runs only on successful release and on the master branch
        run: curl -X POST https://catalogue.nodered.org/add/node/YOUR_NODE_NAME
        env:
          NODE_RED_NODE_NAME: node-red-contrib-tcp-client2
