name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '20' 
      - uses: actions/setup-node@v3
        with:
          node-version: '20' 
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - run: npx semantic-release
